riichi/chombo.club

calendar.md, en/calendar.md
I have achieved responsiveness.
=> Set calendar widget's width to `100%`

Dockerfile, Gemfile, Gemfile.lock
=> build: move to ruby Docker image, rebuild Gemfile.lock

Gemfile, Gemfile.lock
also:
* unpin `jekyll-feed`
* drop windows-specifics deps
=> build: `bundle lock --update`

Dockerfile, README.md, docker-compose.yml
Speeds up consecutive builds a bit.
=> Add minimal docker-compose.yml, improve Dockerfile layering

about.md
=> Add link to statute

Dockerfile
See https://github.com/riichi/chombo.club/runs/6661348908.
=> Hotfix for #38

_posts/2022-07-09-krakow-mers-open.markdown, _posts/en/2022-07-09-krakow-mers-open.markdown
ran locally, looks pretty cool
=> MERS 2022: update fee & referee info

_data/ui-text.yml, about.md, en/about.md
The goal is to make Google return us for the "kcc mahjong club" query.
=> Add KCC/KKC abbreviations for SEO

_data/en/navigation.yml, _data/pl/navigation.yml
=> Add hand.chombo.club to top navbar

about.md, en/about.md
=> Add association authorities and audit commitee members

_data/help/interactive.yml, _data/help/online.yml
=> Add Mahjong Tracker to the help page, fix Tenhou English UI links

_data/ui-text.yml
Reported by `@Olcza` via Discord.
=> fix: minor grammar mistake in site description

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-01 00:13:46.757969+01:00
=> chore: update to 2023-11-01 00:13

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-01 20:42:13.477229+01:00
=> chore: update to 2023-11-01 20:42

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-01 20:50:14.722399+01:00
=> chore: update to 2023-11-01 20:50

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-02 01:07:39.510520+01:00
=> chore: update to 2023-11-02 01:07

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-02 18:54:15.281327+01:00
=> chore: update to 2023-11-02 18:54

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-02 19:00:10.718003+01:00
=> chore: update to 2023-11-02 19:00

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-02 21:37:02.341835+01:00
=> chore: update to 2023-11-02 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-03 09:37:02.154854+01:00
=> chore: update to 2023-11-03 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-03 15:37:02.754089+01:00
=> chore: update to 2023-11-03 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-03 21:37:10.538633+01:00
=> chore: update to 2023-11-03 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-03 22:07:08.610137+01:00
=> chore: update to 2023-11-03 22:07

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-03 23:17:57.627038+01:00
=> chore: update to 2023-11-03 23:17

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-04 00:00:04.476658+01:00
=> chore: update to 2023-11-04 00:00

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-04 00:20:56.441920+01:00
=> chore: update to 2023-11-04 00:20

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-04 09:37:11.020226+01:00
=> chore: update to 2023-11-04 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-04 15:37:11.173207+01:00
=> chore: update to 2023-11-04 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-04 21:37:12.335614+01:00
=> chore: update to 2023-11-04 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-05 21:37:12.046042+01:00
=> chore: update to 2023-11-05 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-08 21:37:12.655594+01:00
=> chore: update to 2023-11-08 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-09 15:37:12.653259+01:00
=> chore: update to 2023-11-09 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-11 21:37:05.654811+01:00
=> chore: update to 2023-11-11 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-12 15:37:12.345952+01:00
=> chore: update to 2023-11-12 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-12 21:37:10.990460+01:00
=> chore: update to 2023-11-12 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-13 09:37:12.433295+01:00
=> chore: update to 2023-11-13 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-13 15:37:06.947971+01:00
=> chore: update to 2023-11-13 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-13 21:37:03.179051+01:00
=> chore: update to 2023-11-13 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-14 09:37:05.569795+01:00
=> chore: update to 2023-11-14 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-14 21:37:12.300179+01:00
=> chore: update to 2023-11-14 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-15 09:37:11.361479+01:00
=> chore: update to 2023-11-15 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-15 15:37:12.545169+01:00
=> chore: update to 2023-11-15 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-15 21:37:12.421714+01:00
=> chore: update to 2023-11-15 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-16 09:37:12.808305+01:00
=> chore: update to 2023-11-16 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-16 15:37:05.016605+01:00
=> chore: update to 2023-11-16 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-16 21:37:12.398322+01:00
=> chore: update to 2023-11-16 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-17 15:37:04.275557+01:00
=> chore: update to 2023-11-17 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-17 21:37:03.337748+01:00
=> chore: update to 2023-11-17 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-19 09:37:04.052120+01:00
=> chore: update to 2023-11-19 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-20 09:37:02.952673+01:00
=> chore: update to 2023-11-20 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-20 21:37:03.957635+01:00
=> chore: update to 2023-11-20 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-22 09:37:12.645770+01:00
=> chore: update to 2023-11-22 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-22 15:43:15.258612+01:00
=> chore: update to 2023-11-22 15:43

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-22 21:37:12.061196+01:00
=> chore: update to 2023-11-22 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-23 09:37:04.165922+01:00
=> chore: update to 2023-11-23 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-23 15:37:04.710394+01:00
=> chore: update to 2023-11-23 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-24 09:37:12.645648+01:00
=> chore: update to 2023-11-24 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-25 18:00:01.157680+01:00
=> chore: update to 2023-11-25 18:00

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-25 18:10:44.849430+01:00
=> chore: update to 2023-11-25 18:10

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-26 15:37:04.314564+01:00
=> chore: update to 2023-11-26 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-27 09:37:06.377936+01:00
=> chore: update to 2023-11-27 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-28 09:37:04.077199+01:00
=> chore: update to 2023-11-28 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-28 21:37:12.447627+01:00
=> chore: update to 2023-11-28 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-30 15:37:12.209427+01:00
=> chore: update to 2023-11-30 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-11-30 21:37:03.925348+01:00
=> chore: update to 2023-11-30 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-12-09 09:37:03.718411+01:00
=> chore: update to 2023-12-09 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-12-12 15:37:03.741304+01:00
=> chore: update to 2023-12-12 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-12-12 21:37:03.646805+01:00
=> chore: update to 2023-12-12 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2023-12-27 15:37:12.447953+01:00
=> chore: update to 2023-12-27 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-03 21:37:12.121304+01:00
=> chore: update to 2024-01-03 21:37

about.md
=> feat: add info about składka

_posts/2022-07-09-krakow-mers-open.markdown, _posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2022-07-09-krakow-mers-open.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown, assets/css/main.scss
=> feat: Hatsumi taikai entry fee, agenda, more referees

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-14 21:42:02.444529+01:00
=> chore: update to 2024-01-14 21:42

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-17 09:37:08.734428+01:00
=> chore: update to 2024-01-17 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-18 18:31:30.977722+01:00
=> chore: update to 2024-01-18 18:31

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-18 21:37:09.199563+01:00
=> chore: update to 2024-01-18 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-19 15:37:12.574372+01:00
=> chore: update to 2024-01-19 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 21:24:22.216713+01:00
=> chore: update to 2024-01-21 21:24

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 21:34:08.247609+01:00
=> chore: update to 2024-01-21 21:34

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 21:53:18.452822+01:00
=> chore: update to 2024-01-21 21:53

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 22:18:19.848018+01:00
=> chore: update to 2024-01-21 22:18

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 22:56:09.267023+01:00
=> chore: update to 2024-01-21 22:56

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-21 23:13:20.375678+01:00
=> chore: update to 2024-01-21 23:13

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-22 09:37:07.991691+01:00
=> chore: update to 2024-01-22 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-22 21:37:12.816307+01:00
=> chore: update to 2024-01-22 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-24 15:37:12.197295+01:00
=> chore: update to 2024-01-24 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-25 09:37:12.342418+01:00
=> chore: update to 2024-01-25 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-27 15:37:06.459961+01:00
=> chore: update to 2024-01-27 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-27 21:37:12.839878+01:00
=> chore: update to 2024-01-27 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-28 15:37:12.647977+01:00
=> chore: update to 2024-01-28 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-29 15:37:12.325658+01:00
=> chore: update to 2024-01-29 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-30 15:37:02.780681+01:00
=> chore: update to 2024-01-30 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-30 21:37:12.562567+01:00
=> chore: update to 2024-01-30 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-31 09:37:09.941162+01:00
=> chore: update to 2024-01-31 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-01-31 21:37:05.506538+01:00
=> chore: update to 2024-01-31 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-01 15:37:11.566598+01:00
=> chore: update to 2024-02-01 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-01 21:37:12.643992+01:00
=> chore: update to 2024-02-01 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-02 15:37:04.084431+01:00
=> chore: update to 2024-02-02 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-03 15:37:06.107671+01:00
=> chore: update to 2024-02-03 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-04 21:37:12.576355+01:00
=> chore: update to 2024-02-04 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-05 15:37:12.674679+01:00
=> chore: update to 2024-02-05 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-06 09:37:03.030393+01:00
=> chore: update to 2024-02-06 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-06 15:37:13.387171+01:00
=> chore: update to 2024-02-06 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-06 21:37:04.050230+01:00
=> chore: update to 2024-02-06 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-07 09:37:12.697326+01:00
=> chore: update to 2024-02-07 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-07 15:37:05.602633+01:00
=> chore: update to 2024-02-07 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-08 15:37:12.057070+01:00
=> chore: update to 2024-02-08 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-09 09:37:02.505166+01:00
=> chore: update to 2024-02-09 09:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-09 21:37:12.779865+01:00
=> chore: update to 2024-02-09 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-12 15:37:12.762462+01:00
=> chore: update to 2024-02-12 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-14 15:37:08.480111+01:00
=> chore: update to 2024-02-14 15:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-14 21:37:09.212197+01:00
=> chore: update to 2024-02-14 21:37

_posts/2023-10-06-hatsumi-taikai.markdown, _posts/en/2023-10-06-hatsumi-taikai.markdown
Automatic update of the website posts. Data retrieval timestamp: 2024-02-17 15:37:13.339618+01:00
=> chore: update to 2024-02-17 15:37

.pre-commit-config.yaml, _posts/2024-12-13-how-to-buy-mahjong-set.markdown, assets/css/main.scss, docker-compose.yml
=> add all cell borders to the set comparison table
